plugins {
    id 'java-library'
    id 'maven-publish'
}


var github_name = System.getenv('GITHUB_USERNAME')

repositories {
    maven {
        name = 'Java-Libraries'
        url = uri('https://maven.pkg.github.com/' + github_name + '/Java-Libraries')
        credentials {
            username = github_name
            password = System.getenv('GITHUB_TOKEN')
        }
    }
}


dependencies {
    implementation('com.github.try.jam:common:0.2.5')
    implementation("com.github.try.jsf:colors:1.0.4")
    compileOnly('org.jetbrains:annotations:24.0.0')


    testImplementation(platform('org.junit:junit-bom:5.10.0'))
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')
}

test {
    useJUnitPlatform()
}